export enum Roles {
    AMMINISTRATORE="AMMINISTRATORE",
    SUPERVISORE="SUPERVISORE",
    LESSICOGRAFO="LESSICOGRAFO",
    ANNOTATORE="ANNOTATORE",
    LESSICOGRAFO_ANNOTATORE="LESSICOGRAFO_ANNOTATORE",
    UTENTE_VIEWER="UTENTE_VIEWER"

}
