/**
 * Enumerazione dei tipi di tile previsti 
 * @example LEXICON = "LEXICON"
 */
export enum TileType {
    TEXT = "TEXT",
    ONTOLOGY_EXPLORER = "ONTOLOGY_EXPLORER",
    ONTOLOGY_CLASS_VIEWER = "ONTOLOGY_VIEWER",
    LEXICON = "LEXICON",
    CORPUS = "CORPUS",
    LAYERS_LIST = "LAYERS_LIST",
    LEXICON_EDIT = "LEXICON_EDIT",
    SEARCH = "SEARCH",
    DICTIONARY = "DICTIONARY",
    DICTIONARY_EDIT = "DICTIONARY_EDIT"
}
